# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.directory_backup_routing_rules_api import DirectoryBackupRoutingRulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDirectoryBackupRoutingRulesApi(unittest.TestCase):
    """DirectoryBackupRoutingRulesApi unit test stubs"""

    def setUp(self):
        self.api = DirectoryBackupRoutingRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_routing_rule(self):
        """Test case for add_routing_rule

        Add directory backup routing rule  # noqa: E501
        """
        pass

    def test_delete_routing_rule(self):
        """Test case for delete_routing_rule

        Delete directory backup routing rule  # noqa: E501
        """
        pass

    def test_get_routing_rule(self):
        """Test case for get_routing_rule

        Get directory backup routing rule  # noqa: E501
        """
        pass

    def test_list_routing_rule(self):
        """Test case for list_routing_rule

        List directory backup routing rules  # noqa: E501
        """
        pass

    def test_update_routing_rule(self):
        """Test case for update_routing_rule

        Update directory backup routing rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
