# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sites_api import SitesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSitesApi(unittest.TestCase):
    """SitesApi unit test stubs"""

    def setUp(self):
        self.api = SitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_site_outbound_caller_numbers(self):
        """Test case for add_site_outbound_caller_numbers

        Add customized outbound caller ID phone numbers  # noqa: E501
        """
        pass

    def test_add_site_setting(self):
        """Test case for add_site_setting

        Add a site setting  # noqa: E501
        """
        pass

    def test_create_phone_site(self):
        """Test case for create_phone_site

        Create a phone site  # noqa: E501
        """
        pass

    def test_delete_phone_site(self):
        """Test case for delete_phone_site

        Delete a phone site  # noqa: E501
        """
        pass

    def test_delete_site_outbound_caller_numbers(self):
        """Test case for delete_site_outbound_caller_numbers

        Remove customized outbound caller ID phone numbers  # noqa: E501
        """
        pass

    def test_delete_site_setting(self):
        """Test case for delete_site_setting

        Delete a site setting  # noqa: E501
        """
        pass

    def test_get_a_site(self):
        """Test case for get_a_site

        Get phone site details  # noqa: E501
        """
        pass

    def test_get_site_policy_details(self):
        """Test case for get_site_policy_details

        Get site policy details  # noqa: E501
        """
        pass

    def test_get_site_setting_for_type(self):
        """Test case for get_site_setting_for_type

        Get a phone site setting  # noqa: E501
        """
        pass

    def test_list_phone_sites(self):
        """Test case for list_phone_sites

        List phone sites  # noqa: E501
        """
        pass

    def test_list_site_customize_outbound_caller_numbers(self):
        """Test case for list_site_customize_outbound_caller_numbers

        List customized outbound caller ID phone numbers  # noqa: E501
        """
        pass

    def test_update_site_details(self):
        """Test case for update_site_details

        Update phone site details  # noqa: E501
        """
        pass

    def test_update_site_policy(self):
        """Test case for update_site_policy

        Update site policy  # noqa: E501
        """
        pass

    def test_update_site_setting(self):
        """Test case for update_site_setting

        Update the site setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
