# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auto_receptionists_api import AutoReceptionistsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutoReceptionistsApi(unittest.TestCase):
    """AutoReceptionistsApi unit test stubs"""

    def setUp(self):
        self.api = AutoReceptionistsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_auto_receptionist(self):
        """Test case for add_auto_receptionist

        Add an auto receptionist  # noqa: E501
        """
        pass

    def test_add_policy(self):
        """Test case for add_policy

        Add a policy setting  # noqa: E501
        """
        pass

    def test_assign_phone_numbers_auto_receptionist(self):
        """Test case for assign_phone_numbers_auto_receptionist

        Assign phone numbers  # noqa: E501
        """
        pass

    def test_delete_auto_receptionist(self):
        """Test case for delete_auto_receptionist

        Delete a non-primary auto receptionist  # noqa: E501
        """
        pass

    def test_delete_policy(self):
        """Test case for delete_policy

        Delete a policy setting  # noqa: E501
        """
        pass

    def test_get_auto_receptionist_detail(self):
        """Test case for get_auto_receptionist_detail

        Get an auto receptionist  # noqa: E501
        """
        pass

    def test_get_auto_receptionists_policy(self):
        """Test case for get_auto_receptionists_policy

        Get an auto receptionist policy  # noqa: E501
        """
        pass

    def test_list_auto_receptionists(self):
        """Test case for list_auto_receptionists

        List auto receptionists  # noqa: E501
        """
        pass

    def test_unassign_a_phone_num_auto_receptionist(self):
        """Test case for unassign_a_phone_num_auto_receptionist

        Unassign a phone number  # noqa: E501
        """
        pass

    def test_unassign_all_phone_nums_auto_receptionist(self):
        """Test case for unassign_all_phone_nums_auto_receptionist

        Unassign all phone numbers  # noqa: E501
        """
        pass

    def test_update_auto_receptionist(self):
        """Test case for update_auto_receptionist

        Update an auto receptionist  # noqa: E501
        """
        pass

    def test_update_auto_receptionist_policy(self):
        """Test case for update_auto_receptionist_policy

        Update an auto receptionist policy  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Update a policy setting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
