# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExtensionIdLineKeysBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'line_keys': 'list[PhoneextensionextensionIdlineKeysLineKeys]'
    }

    attribute_map = {
        'line_keys': 'line_keys'
    }

    def __init__(self, line_keys=None):  # noqa: E501
        """ExtensionIdLineKeysBody - a model defined in Swagger"""  # noqa: E501
        self._line_keys = None
        self.discriminator = None
        if line_keys is not None:
            self.line_keys = line_keys

    @property
    def line_keys(self):
        """Gets the line_keys of this ExtensionIdLineKeysBody.  # noqa: E501

        The line key position.  # noqa: E501

        :return: The line_keys of this ExtensionIdLineKeysBody.  # noqa: E501
        :rtype: list[PhoneextensionextensionIdlineKeysLineKeys]
        """
        return self._line_keys

    @line_keys.setter
    def line_keys(self, line_keys):
        """Sets the line_keys of this ExtensionIdLineKeysBody.

        The line key position.  # noqa: E501

        :param line_keys: The line_keys of this ExtensionIdLineKeysBody.  # noqa: E501
        :type: list[PhoneextensionextensionIdlineKeysLineKeys]
        """

        self._line_keys = line_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExtensionIdLineKeysBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtensionIdLineKeysBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
