# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'id': 'str',
        '_from': 'datetime',
        'to': 'datetime',
        'selected': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'id': 'id',
        '_from': 'from',
        'to': 'to',
        'selected': 'selected'
    }

    def __init__(self, name=None, id=None, _from=None, to=None, selected=None):  # noqa: E501
        """InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._id = None
        self.__from = None
        self._to = None
        self._selected = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if _from is not None:
            self._from = _from
        if to is not None:
            self.to = to
        if selected is not None:
            self.selected = selected

    @property
    def name(self):
        """Gets the name of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501

        The holiday name.  # noqa: E501

        :return: The name of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.

        The holiday name.  # noqa: E501

        :param name: The name of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501

        The holiday ID.  # noqa: E501

        :return: The id of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.

        The holiday ID.  # noqa: E501

        :param id: The id of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def _from(self):
        """Gets the _from of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501

        The holiday start time.  # noqa: E501

        :return: The _from of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :rtype: datetime
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.

        The holiday start time.  # noqa: E501

        :param _from: The _from of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :type: datetime
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501

        The holiday end time.  # noqa: E501

        :return: The to of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :rtype: datetime
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.

        The holiday end time.  # noqa: E501

        :param to: The to of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :type: datetime
        """

        self._to = to

    @property
    def selected(self):
        """Gets the selected of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501

        Whether to select this holiday.  # noqa: E501

        :return: The selected of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :rtype: bool
        """
        return self._selected

    @selected.setter
    def selected(self, selected):
        """Sets the selected of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.

        Whether to select this holiday.  # noqa: E501

        :param selected: The selected of this InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays.  # noqa: E501
        :type: bool
        """

        self._selected = selected

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20022RestrictedCallHoursRestrictedHolidayHoursHolidayHoursHolidays):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
