# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20082ForwardedBy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extension_number': 'str',
        'extension_type': 'str',
        'location': 'str',
        'name': 'str',
        'number_type': 'int',
        'phone_number': 'str'
    }

    attribute_map = {
        'extension_number': 'extension_number',
        'extension_type': 'extension_type',
        'location': 'location',
        'name': 'name',
        'number_type': 'number_type',
        'phone_number': 'phone_number'
    }

    def __init__(self, extension_number=None, extension_type=None, location=None, name=None, number_type=None, phone_number=None):  # noqa: E501
        """InlineResponse20082ForwardedBy - a model defined in Swagger"""  # noqa: E501
        self._extension_number = None
        self._extension_type = None
        self._location = None
        self._name = None
        self._number_type = None
        self._phone_number = None
        self.discriminator = None
        if extension_number is not None:
            self.extension_number = extension_number
        if extension_type is not None:
            self.extension_type = extension_type
        if location is not None:
            self.location = location
        if name is not None:
            self.name = name
        if number_type is not None:
            self.number_type = number_type
        if phone_number is not None:
            self.phone_number = phone_number

    @property
    def extension_number(self):
        """Gets the extension_number of this InlineResponse20082ForwardedBy.  # noqa: E501


        :return: The extension_number of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: str
        """
        return self._extension_number

    @extension_number.setter
    def extension_number(self, extension_number):
        """Sets the extension_number of this InlineResponse20082ForwardedBy.


        :param extension_number: The extension_number of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: str
        """

        self._extension_number = extension_number

    @property
    def extension_type(self):
        """Gets the extension_type of this InlineResponse20082ForwardedBy.  # noqa: E501


        :return: The extension_type of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: str
        """
        return self._extension_type

    @extension_type.setter
    def extension_type(self, extension_type):
        """Sets the extension_type of this InlineResponse20082ForwardedBy.


        :param extension_type: The extension_type of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: str
        """
        allowed_values = ["user", "callQueue", "autoReceptionist", "commonAreaPhone", "sharedLineGroup"]  # noqa: E501
        if extension_type not in allowed_values:
            raise ValueError(
                "Invalid value for `extension_type` ({0}), must be one of {1}"  # noqa: E501
                .format(extension_type, allowed_values)
            )

        self._extension_type = extension_type

    @property
    def location(self):
        """Gets the location of this InlineResponse20082ForwardedBy.  # noqa: E501


        :return: The location of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this InlineResponse20082ForwardedBy.


        :param location: The location of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def name(self):
        """Gets the name of this InlineResponse20082ForwardedBy.  # noqa: E501


        :return: The name of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20082ForwardedBy.


        :param name: The name of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def number_type(self):
        """Gets the number_type of this InlineResponse20082ForwardedBy.  # noqa: E501

        Phone number types: `1` - Extension `2`- E164 number `3` - Custom number.  # noqa: E501

        :return: The number_type of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: int
        """
        return self._number_type

    @number_type.setter
    def number_type(self, number_type):
        """Sets the number_type of this InlineResponse20082ForwardedBy.

        Phone number types: `1` - Extension `2`- E164 number `3` - Custom number.  # noqa: E501

        :param number_type: The number_type of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: int
        """

        self._number_type = number_type

    @property
    def phone_number(self):
        """Gets the phone_number of this InlineResponse20082ForwardedBy.  # noqa: E501


        :return: The phone_number of this InlineResponse20082ForwardedBy.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this InlineResponse20082ForwardedBy.


        :param phone_number: The phone_number of this InlineResponse20082ForwardedBy.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20082ForwardedBy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20082ForwardedBy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
