# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PhoneusersuserIdPolicy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ad_hoc_call_recording': 'PhoneusersuserIdPolicyAdHocCallRecording',
        'auto_call_recording': 'PhoneusersuserIdPolicyAutoCallRecording',
        'call_overflow': 'PhoneusersuserIdPolicyCallOverflow',
        'call_park': 'PhoneusersuserIdPolicyCallPark',
        'call_transferring': 'PhoneusersuserIdPolicyCallTransferring',
        'delegation': 'bool',
        'elevate_to_meeting': 'bool',
        'emergency_address_management': 'PhoneusersuserIdPolicyEmergencyAddressManagement',
        'emergency_calls_to_psap': 'bool',
        'forwarding_to_external_numbers': 'bool',
        'call_handling_forwarding_to_other_users': 'PhoneusersuserIdPolicyCallHandlingForwardingToOtherUsers',
        'hand_off_to_room': 'PhoneusersuserIdPolicyHandOffToRoom',
        'international_calling': 'bool',
        'mobile_switch_to_carrier': 'PhoneusersuserIdPolicyMobileSwitchToCarrier',
        'select_outbound_caller_id': 'PhoneusersuserIdPolicySelectOutboundCallerId',
        'sms': 'PhoneusersuserIdPolicySms',
        'voicemail': 'PhoneusersuserIdPolicyVoicemail',
        'voicemail_access_members': 'list[PhoneusersuserIdPolicyVoicemailAccessMembers]',
        'zoom_phone_on_mobile': 'PhoneusersuserIdPolicyZoomPhoneOnMobile',
        'personal_audio_library': 'PhoneusersuserIdPolicyPersonalAudioLibrary',
        'voicemail_transcription': 'PhoneusersuserIdPolicyVoicemailTranscription',
        'voicemail_notification_by_email': 'PhoneusersuserIdPolicyVoicemailNotificationByEmail',
        'shared_voicemail_notification_by_email': 'PhoneusersuserIdPolicySharedVoicemailNotificationByEmail',
        'check_voicemails_over_phone': 'PhoneusersuserIdPolicyCheckVoicemailsOverPhone',
        'audio_intercom': 'PhoneusersuserIdPolicyAudioIntercom',
        'e2e_encryption': 'PhoneusersuserIdPolicyE2eEncryption'
    }

    attribute_map = {
        'ad_hoc_call_recording': 'ad_hoc_call_recording',
        'auto_call_recording': 'auto_call_recording',
        'call_overflow': 'call_overflow',
        'call_park': 'call_park',
        'call_transferring': 'call_transferring',
        'delegation': 'delegation',
        'elevate_to_meeting': 'elevate_to_meeting',
        'emergency_address_management': 'emergency_address_management',
        'emergency_calls_to_psap': 'emergency_calls_to_psap',
        'forwarding_to_external_numbers': 'forwarding_to_external_numbers',
        'call_handling_forwarding_to_other_users': 'call_handling_forwarding_to_other_users',
        'hand_off_to_room': 'hand_off_to_room',
        'international_calling': 'international_calling',
        'mobile_switch_to_carrier': 'mobile_switch_to_carrier',
        'select_outbound_caller_id': 'select_outbound_caller_id',
        'sms': 'sms',
        'voicemail': 'voicemail',
        'voicemail_access_members': 'voicemail_access_members',
        'zoom_phone_on_mobile': 'zoom_phone_on_mobile',
        'personal_audio_library': 'personal_audio_library',
        'voicemail_transcription': 'voicemail_transcription',
        'voicemail_notification_by_email': 'voicemail_notification_by_email',
        'shared_voicemail_notification_by_email': 'shared_voicemail_notification_by_email',
        'check_voicemails_over_phone': 'check_voicemails_over_phone',
        'audio_intercom': 'audio_intercom',
        'e2e_encryption': 'e2e_encryption'
    }

    def __init__(self, ad_hoc_call_recording=None, auto_call_recording=None, call_overflow=None, call_park=None, call_transferring=None, delegation=None, elevate_to_meeting=None, emergency_address_management=None, emergency_calls_to_psap=None, forwarding_to_external_numbers=None, call_handling_forwarding_to_other_users=None, hand_off_to_room=None, international_calling=None, mobile_switch_to_carrier=None, select_outbound_caller_id=None, sms=None, voicemail=None, voicemail_access_members=None, zoom_phone_on_mobile=None, personal_audio_library=None, voicemail_transcription=None, voicemail_notification_by_email=None, shared_voicemail_notification_by_email=None, check_voicemails_over_phone=None, audio_intercom=None, e2e_encryption=None):  # noqa: E501
        """PhoneusersuserIdPolicy - a model defined in Swagger"""  # noqa: E501
        self._ad_hoc_call_recording = None
        self._auto_call_recording = None
        self._call_overflow = None
        self._call_park = None
        self._call_transferring = None
        self._delegation = None
        self._elevate_to_meeting = None
        self._emergency_address_management = None
        self._emergency_calls_to_psap = None
        self._forwarding_to_external_numbers = None
        self._call_handling_forwarding_to_other_users = None
        self._hand_off_to_room = None
        self._international_calling = None
        self._mobile_switch_to_carrier = None
        self._select_outbound_caller_id = None
        self._sms = None
        self._voicemail = None
        self._voicemail_access_members = None
        self._zoom_phone_on_mobile = None
        self._personal_audio_library = None
        self._voicemail_transcription = None
        self._voicemail_notification_by_email = None
        self._shared_voicemail_notification_by_email = None
        self._check_voicemails_over_phone = None
        self._audio_intercom = None
        self._e2e_encryption = None
        self.discriminator = None
        if ad_hoc_call_recording is not None:
            self.ad_hoc_call_recording = ad_hoc_call_recording
        if auto_call_recording is not None:
            self.auto_call_recording = auto_call_recording
        if call_overflow is not None:
            self.call_overflow = call_overflow
        if call_park is not None:
            self.call_park = call_park
        if call_transferring is not None:
            self.call_transferring = call_transferring
        if delegation is not None:
            self.delegation = delegation
        if elevate_to_meeting is not None:
            self.elevate_to_meeting = elevate_to_meeting
        if emergency_address_management is not None:
            self.emergency_address_management = emergency_address_management
        if emergency_calls_to_psap is not None:
            self.emergency_calls_to_psap = emergency_calls_to_psap
        if forwarding_to_external_numbers is not None:
            self.forwarding_to_external_numbers = forwarding_to_external_numbers
        if call_handling_forwarding_to_other_users is not None:
            self.call_handling_forwarding_to_other_users = call_handling_forwarding_to_other_users
        if hand_off_to_room is not None:
            self.hand_off_to_room = hand_off_to_room
        if international_calling is not None:
            self.international_calling = international_calling
        if mobile_switch_to_carrier is not None:
            self.mobile_switch_to_carrier = mobile_switch_to_carrier
        if select_outbound_caller_id is not None:
            self.select_outbound_caller_id = select_outbound_caller_id
        if sms is not None:
            self.sms = sms
        if voicemail is not None:
            self.voicemail = voicemail
        if voicemail_access_members is not None:
            self.voicemail_access_members = voicemail_access_members
        if zoom_phone_on_mobile is not None:
            self.zoom_phone_on_mobile = zoom_phone_on_mobile
        if personal_audio_library is not None:
            self.personal_audio_library = personal_audio_library
        if voicemail_transcription is not None:
            self.voicemail_transcription = voicemail_transcription
        if voicemail_notification_by_email is not None:
            self.voicemail_notification_by_email = voicemail_notification_by_email
        if shared_voicemail_notification_by_email is not None:
            self.shared_voicemail_notification_by_email = shared_voicemail_notification_by_email
        if check_voicemails_over_phone is not None:
            self.check_voicemails_over_phone = check_voicemails_over_phone
        if audio_intercom is not None:
            self.audio_intercom = audio_intercom
        if e2e_encryption is not None:
            self.e2e_encryption = e2e_encryption

    @property
    def ad_hoc_call_recording(self):
        """Gets the ad_hoc_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The ad_hoc_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyAdHocCallRecording
        """
        return self._ad_hoc_call_recording

    @ad_hoc_call_recording.setter
    def ad_hoc_call_recording(self, ad_hoc_call_recording):
        """Sets the ad_hoc_call_recording of this PhoneusersuserIdPolicy.


        :param ad_hoc_call_recording: The ad_hoc_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyAdHocCallRecording
        """

        self._ad_hoc_call_recording = ad_hoc_call_recording

    @property
    def auto_call_recording(self):
        """Gets the auto_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The auto_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyAutoCallRecording
        """
        return self._auto_call_recording

    @auto_call_recording.setter
    def auto_call_recording(self, auto_call_recording):
        """Sets the auto_call_recording of this PhoneusersuserIdPolicy.


        :param auto_call_recording: The auto_call_recording of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyAutoCallRecording
        """

        self._auto_call_recording = auto_call_recording

    @property
    def call_overflow(self):
        """Gets the call_overflow of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The call_overflow of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyCallOverflow
        """
        return self._call_overflow

    @call_overflow.setter
    def call_overflow(self, call_overflow):
        """Sets the call_overflow of this PhoneusersuserIdPolicy.


        :param call_overflow: The call_overflow of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyCallOverflow
        """

        self._call_overflow = call_overflow

    @property
    def call_park(self):
        """Gets the call_park of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The call_park of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyCallPark
        """
        return self._call_park

    @call_park.setter
    def call_park(self, call_park):
        """Sets the call_park of this PhoneusersuserIdPolicy.


        :param call_park: The call_park of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyCallPark
        """

        self._call_park = call_park

    @property
    def call_transferring(self):
        """Gets the call_transferring of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The call_transferring of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyCallTransferring
        """
        return self._call_transferring

    @call_transferring.setter
    def call_transferring(self, call_transferring):
        """Sets the call_transferring of this PhoneusersuserIdPolicy.


        :param call_transferring: The call_transferring of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyCallTransferring
        """

        self._call_transferring = call_transferring

    @property
    def delegation(self):
        """Gets the delegation of this PhoneusersuserIdPolicy.  # noqa: E501

        Whether the user can use [call delegation](https://support.zoom.us/hc/en-us/articles/360032881731-Setting-up-call-delegation-shared-lines-appearance-).  # noqa: E501

        :return: The delegation of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._delegation

    @delegation.setter
    def delegation(self, delegation):
        """Sets the delegation of this PhoneusersuserIdPolicy.

        Whether the user can use [call delegation](https://support.zoom.us/hc/en-us/articles/360032881731-Setting-up-call-delegation-shared-lines-appearance-).  # noqa: E501

        :param delegation: The delegation of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: bool
        """

        self._delegation = delegation

    @property
    def elevate_to_meeting(self):
        """Gets the elevate_to_meeting of this PhoneusersuserIdPolicy.  # noqa: E501

        Whether the user can elevate their phone calls to a meeting.  # noqa: E501

        :return: The elevate_to_meeting of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._elevate_to_meeting

    @elevate_to_meeting.setter
    def elevate_to_meeting(self, elevate_to_meeting):
        """Sets the elevate_to_meeting of this PhoneusersuserIdPolicy.

        Whether the user can elevate their phone calls to a meeting.  # noqa: E501

        :param elevate_to_meeting: The elevate_to_meeting of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: bool
        """

        self._elevate_to_meeting = elevate_to_meeting

    @property
    def emergency_address_management(self):
        """Gets the emergency_address_management of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The emergency_address_management of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyEmergencyAddressManagement
        """
        return self._emergency_address_management

    @emergency_address_management.setter
    def emergency_address_management(self, emergency_address_management):
        """Sets the emergency_address_management of this PhoneusersuserIdPolicy.


        :param emergency_address_management: The emergency_address_management of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyEmergencyAddressManagement
        """

        self._emergency_address_management = emergency_address_management

    @property
    def emergency_calls_to_psap(self):
        """Gets the emergency_calls_to_psap of this PhoneusersuserIdPolicy.  # noqa: E501

        When disabled, emergency calls placed by the user will not be delivered to the Public Safety Answering Point(PSAP), but still will be delivered to the Internal Safety Response Team based on the settings.  # noqa: E501

        :return: The emergency_calls_to_psap of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._emergency_calls_to_psap

    @emergency_calls_to_psap.setter
    def emergency_calls_to_psap(self, emergency_calls_to_psap):
        """Sets the emergency_calls_to_psap of this PhoneusersuserIdPolicy.

        When disabled, emergency calls placed by the user will not be delivered to the Public Safety Answering Point(PSAP), but still will be delivered to the Internal Safety Response Team based on the settings.  # noqa: E501

        :param emergency_calls_to_psap: The emergency_calls_to_psap of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: bool
        """

        self._emergency_calls_to_psap = emergency_calls_to_psap

    @property
    def forwarding_to_external_numbers(self):
        """Gets the forwarding_to_external_numbers of this PhoneusersuserIdPolicy.  # noqa: E501

        Whether to allow call forwarding to external numbers. Use the `call_handling_forwarding_to_other_users` instead.  # noqa: E501

        :return: The forwarding_to_external_numbers of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._forwarding_to_external_numbers

    @forwarding_to_external_numbers.setter
    def forwarding_to_external_numbers(self, forwarding_to_external_numbers):
        """Sets the forwarding_to_external_numbers of this PhoneusersuserIdPolicy.

        Whether to allow call forwarding to external numbers. Use the `call_handling_forwarding_to_other_users` instead.  # noqa: E501

        :param forwarding_to_external_numbers: The forwarding_to_external_numbers of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: bool
        """

        self._forwarding_to_external_numbers = forwarding_to_external_numbers

    @property
    def call_handling_forwarding_to_other_users(self):
        """Gets the call_handling_forwarding_to_other_users of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The call_handling_forwarding_to_other_users of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyCallHandlingForwardingToOtherUsers
        """
        return self._call_handling_forwarding_to_other_users

    @call_handling_forwarding_to_other_users.setter
    def call_handling_forwarding_to_other_users(self, call_handling_forwarding_to_other_users):
        """Sets the call_handling_forwarding_to_other_users of this PhoneusersuserIdPolicy.


        :param call_handling_forwarding_to_other_users: The call_handling_forwarding_to_other_users of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyCallHandlingForwardingToOtherUsers
        """

        self._call_handling_forwarding_to_other_users = call_handling_forwarding_to_other_users

    @property
    def hand_off_to_room(self):
        """Gets the hand_off_to_room of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The hand_off_to_room of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyHandOffToRoom
        """
        return self._hand_off_to_room

    @hand_off_to_room.setter
    def hand_off_to_room(self, hand_off_to_room):
        """Sets the hand_off_to_room of this PhoneusersuserIdPolicy.


        :param hand_off_to_room: The hand_off_to_room of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyHandOffToRoom
        """

        self._hand_off_to_room = hand_off_to_room

    @property
    def international_calling(self):
        """Gets the international_calling of this PhoneusersuserIdPolicy.  # noqa: E501

        Whether the current extension can make international calls outside of their calling plan.  # noqa: E501

        :return: The international_calling of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._international_calling

    @international_calling.setter
    def international_calling(self, international_calling):
        """Sets the international_calling of this PhoneusersuserIdPolicy.

        Whether the current extension can make international calls outside of their calling plan.  # noqa: E501

        :param international_calling: The international_calling of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: bool
        """

        self._international_calling = international_calling

    @property
    def mobile_switch_to_carrier(self):
        """Gets the mobile_switch_to_carrier of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The mobile_switch_to_carrier of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyMobileSwitchToCarrier
        """
        return self._mobile_switch_to_carrier

    @mobile_switch_to_carrier.setter
    def mobile_switch_to_carrier(self, mobile_switch_to_carrier):
        """Sets the mobile_switch_to_carrier of this PhoneusersuserIdPolicy.


        :param mobile_switch_to_carrier: The mobile_switch_to_carrier of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyMobileSwitchToCarrier
        """

        self._mobile_switch_to_carrier = mobile_switch_to_carrier

    @property
    def select_outbound_caller_id(self):
        """Gets the select_outbound_caller_id of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The select_outbound_caller_id of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicySelectOutboundCallerId
        """
        return self._select_outbound_caller_id

    @select_outbound_caller_id.setter
    def select_outbound_caller_id(self, select_outbound_caller_id):
        """Sets the select_outbound_caller_id of this PhoneusersuserIdPolicy.


        :param select_outbound_caller_id: The select_outbound_caller_id of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicySelectOutboundCallerId
        """

        self._select_outbound_caller_id = select_outbound_caller_id

    @property
    def sms(self):
        """Gets the sms of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The sms of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicySms
        """
        return self._sms

    @sms.setter
    def sms(self, sms):
        """Sets the sms of this PhoneusersuserIdPolicy.


        :param sms: The sms of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicySms
        """

        self._sms = sms

    @property
    def voicemail(self):
        """Gets the voicemail of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The voicemail of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyVoicemail
        """
        return self._voicemail

    @voicemail.setter
    def voicemail(self, voicemail):
        """Sets the voicemail of this PhoneusersuserIdPolicy.


        :param voicemail: The voicemail of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyVoicemail
        """

        self._voicemail = voicemail

    @property
    def voicemail_access_members(self):
        """Gets the voicemail_access_members of this PhoneusersuserIdPolicy.  # noqa: E501

        This field updates a voicemail setting. <b>Deprecated:</b> we will completely deprecate this property in a future release. Use `Add/Update/Delete a user's shared access setting` API instead, with settingType 'voice-mail' to manage the voicemail access members.  # noqa: E501

        :return: The voicemail_access_members of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: list[PhoneusersuserIdPolicyVoicemailAccessMembers]
        """
        return self._voicemail_access_members

    @voicemail_access_members.setter
    def voicemail_access_members(self, voicemail_access_members):
        """Sets the voicemail_access_members of this PhoneusersuserIdPolicy.

        This field updates a voicemail setting. <b>Deprecated:</b> we will completely deprecate this property in a future release. Use `Add/Update/Delete a user's shared access setting` API instead, with settingType 'voice-mail' to manage the voicemail access members.  # noqa: E501

        :param voicemail_access_members: The voicemail_access_members of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: list[PhoneusersuserIdPolicyVoicemailAccessMembers]
        """

        self._voicemail_access_members = voicemail_access_members

    @property
    def zoom_phone_on_mobile(self):
        """Gets the zoom_phone_on_mobile of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The zoom_phone_on_mobile of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyZoomPhoneOnMobile
        """
        return self._zoom_phone_on_mobile

    @zoom_phone_on_mobile.setter
    def zoom_phone_on_mobile(self, zoom_phone_on_mobile):
        """Sets the zoom_phone_on_mobile of this PhoneusersuserIdPolicy.


        :param zoom_phone_on_mobile: The zoom_phone_on_mobile of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyZoomPhoneOnMobile
        """

        self._zoom_phone_on_mobile = zoom_phone_on_mobile

    @property
    def personal_audio_library(self):
        """Gets the personal_audio_library of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The personal_audio_library of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyPersonalAudioLibrary
        """
        return self._personal_audio_library

    @personal_audio_library.setter
    def personal_audio_library(self, personal_audio_library):
        """Sets the personal_audio_library of this PhoneusersuserIdPolicy.


        :param personal_audio_library: The personal_audio_library of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyPersonalAudioLibrary
        """

        self._personal_audio_library = personal_audio_library

    @property
    def voicemail_transcription(self):
        """Gets the voicemail_transcription of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The voicemail_transcription of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyVoicemailTranscription
        """
        return self._voicemail_transcription

    @voicemail_transcription.setter
    def voicemail_transcription(self, voicemail_transcription):
        """Sets the voicemail_transcription of this PhoneusersuserIdPolicy.


        :param voicemail_transcription: The voicemail_transcription of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyVoicemailTranscription
        """

        self._voicemail_transcription = voicemail_transcription

    @property
    def voicemail_notification_by_email(self):
        """Gets the voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyVoicemailNotificationByEmail
        """
        return self._voicemail_notification_by_email

    @voicemail_notification_by_email.setter
    def voicemail_notification_by_email(self, voicemail_notification_by_email):
        """Sets the voicemail_notification_by_email of this PhoneusersuserIdPolicy.


        :param voicemail_notification_by_email: The voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyVoicemailNotificationByEmail
        """

        self._voicemail_notification_by_email = voicemail_notification_by_email

    @property
    def shared_voicemail_notification_by_email(self):
        """Gets the shared_voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The shared_voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicySharedVoicemailNotificationByEmail
        """
        return self._shared_voicemail_notification_by_email

    @shared_voicemail_notification_by_email.setter
    def shared_voicemail_notification_by_email(self, shared_voicemail_notification_by_email):
        """Sets the shared_voicemail_notification_by_email of this PhoneusersuserIdPolicy.


        :param shared_voicemail_notification_by_email: The shared_voicemail_notification_by_email of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicySharedVoicemailNotificationByEmail
        """

        self._shared_voicemail_notification_by_email = shared_voicemail_notification_by_email

    @property
    def check_voicemails_over_phone(self):
        """Gets the check_voicemails_over_phone of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The check_voicemails_over_phone of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyCheckVoicemailsOverPhone
        """
        return self._check_voicemails_over_phone

    @check_voicemails_over_phone.setter
    def check_voicemails_over_phone(self, check_voicemails_over_phone):
        """Sets the check_voicemails_over_phone of this PhoneusersuserIdPolicy.


        :param check_voicemails_over_phone: The check_voicemails_over_phone of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyCheckVoicemailsOverPhone
        """

        self._check_voicemails_over_phone = check_voicemails_over_phone

    @property
    def audio_intercom(self):
        """Gets the audio_intercom of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The audio_intercom of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyAudioIntercom
        """
        return self._audio_intercom

    @audio_intercom.setter
    def audio_intercom(self, audio_intercom):
        """Sets the audio_intercom of this PhoneusersuserIdPolicy.


        :param audio_intercom: The audio_intercom of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyAudioIntercom
        """

        self._audio_intercom = audio_intercom

    @property
    def e2e_encryption(self):
        """Gets the e2e_encryption of this PhoneusersuserIdPolicy.  # noqa: E501


        :return: The e2e_encryption of this PhoneusersuserIdPolicy.  # noqa: E501
        :rtype: PhoneusersuserIdPolicyE2eEncryption
        """
        return self._e2e_encryption

    @e2e_encryption.setter
    def e2e_encryption(self, e2e_encryption):
        """Sets the e2e_encryption of this PhoneusersuserIdPolicy.


        :param e2e_encryption: The e2e_encryption of this PhoneusersuserIdPolicy.  # noqa: E501
        :type: PhoneusersuserIdPolicyE2eEncryption
        """

        self._e2e_encryption = e2e_encryption

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhoneusersuserIdPolicy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhoneusersuserIdPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
