# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PhonecommonAreaPhonescommonAreaPhoneIdPolicy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hot_desking': 'PhonecommonAreaPhonescommonAreaPhoneIdPolicyHotDesking',
        'international_calling': 'PhonecommonAreaPhonescommonAreaPhoneIdPolicyInternationalCalling',
        'select_outbound_caller_id': 'PhonecommonAreaPhonescommonAreaPhoneIdPolicySelectOutboundCallerId'
    }

    attribute_map = {
        'hot_desking': 'hot_desking',
        'international_calling': 'international_calling',
        'select_outbound_caller_id': 'select_outbound_caller_id'
    }

    def __init__(self, hot_desking=None, international_calling=None, select_outbound_caller_id=None):  # noqa: E501
        """PhonecommonAreaPhonescommonAreaPhoneIdPolicy - a model defined in Swagger"""  # noqa: E501
        self._hot_desking = None
        self._international_calling = None
        self._select_outbound_caller_id = None
        self.discriminator = None
        if hot_desking is not None:
            self.hot_desking = hot_desking
        if international_calling is not None:
            self.international_calling = international_calling
        if select_outbound_caller_id is not None:
            self.select_outbound_caller_id = select_outbound_caller_id

    @property
    def hot_desking(self):
        """Gets the hot_desking of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501


        :return: The hot_desking of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :rtype: PhonecommonAreaPhonescommonAreaPhoneIdPolicyHotDesking
        """
        return self._hot_desking

    @hot_desking.setter
    def hot_desking(self, hot_desking):
        """Sets the hot_desking of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.


        :param hot_desking: The hot_desking of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :type: PhonecommonAreaPhonescommonAreaPhoneIdPolicyHotDesking
        """

        self._hot_desking = hot_desking

    @property
    def international_calling(self):
        """Gets the international_calling of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501


        :return: The international_calling of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :rtype: PhonecommonAreaPhonescommonAreaPhoneIdPolicyInternationalCalling
        """
        return self._international_calling

    @international_calling.setter
    def international_calling(self, international_calling):
        """Sets the international_calling of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.


        :param international_calling: The international_calling of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :type: PhonecommonAreaPhonescommonAreaPhoneIdPolicyInternationalCalling
        """

        self._international_calling = international_calling

    @property
    def select_outbound_caller_id(self):
        """Gets the select_outbound_caller_id of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501


        :return: The select_outbound_caller_id of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :rtype: PhonecommonAreaPhonescommonAreaPhoneIdPolicySelectOutboundCallerId
        """
        return self._select_outbound_caller_id

    @select_outbound_caller_id.setter
    def select_outbound_caller_id(self, select_outbound_caller_id):
        """Sets the select_outbound_caller_id of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.


        :param select_outbound_caller_id: The select_outbound_caller_id of this PhonecommonAreaPhonescommonAreaPhoneIdPolicy.  # noqa: E501
        :type: PhonecommonAreaPhonescommonAreaPhoneIdPolicySelectOutboundCallerId
        """

        self._select_outbound_caller_id = select_outbound_caller_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhonecommonAreaPhonescommonAreaPhoneIdPolicy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhonecommonAreaPhonescommonAreaPhoneIdPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
