# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PhoneProvisionTemplatesBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'content': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'content': 'content'
    }

    def __init__(self, name=None, description=None, content=None):  # noqa: E501
        """PhoneProvisionTemplatesBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._content = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        if content is not None:
            self.content = content

    @property
    def name(self):
        """Gets the name of this PhoneProvisionTemplatesBody.  # noqa: E501

        The template name.  # noqa: E501

        :return: The name of this PhoneProvisionTemplatesBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PhoneProvisionTemplatesBody.

        The template name.  # noqa: E501

        :param name: The name of this PhoneProvisionTemplatesBody.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this PhoneProvisionTemplatesBody.  # noqa: E501

        The provision template description.  # noqa: E501

        :return: The description of this PhoneProvisionTemplatesBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PhoneProvisionTemplatesBody.

        The provision template description.  # noqa: E501

        :param description: The description of this PhoneProvisionTemplatesBody.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def content(self):
        """Gets the content of this PhoneProvisionTemplatesBody.  # noqa: E501

        The [content of the provision template](https://support.zoom.us/hc/en-us/articles/360035817952#h_6ef0cbf5-8d10-4237-91f0-e70f7b73a590).  # noqa: E501

        :return: The content of this PhoneProvisionTemplatesBody.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this PhoneProvisionTemplatesBody.

        The [content of the provision template](https://support.zoom.us/hc/en-us/articles/360035817952#h_6ef0cbf5-8d10-4237-91f0-e70f7b73a590).  # noqa: E501

        :param content: The content of this PhoneProvisionTemplatesBody.  # noqa: E501
        :type: str
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhoneProvisionTemplatesBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhoneProvisionTemplatesBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
