# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enable': 'bool',
        'reset': 'bool',
        'time_zone': 'PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursTimeZone',
        'allow_internal_calls': 'bool',
        'restricted_hours': 'PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHours',
        'restricted_holiday_hours': 'PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHolidayHours'
    }

    attribute_map = {
        'enable': 'enable',
        'reset': 'reset',
        'time_zone': 'time_zone',
        'allow_internal_calls': 'allow_internal_calls',
        'restricted_hours': 'restricted_hours',
        'restricted_holiday_hours': 'restricted_holiday_hours'
    }

    def __init__(self, enable=None, reset=None, time_zone=None, allow_internal_calls=None, restricted_hours=None, restricted_holiday_hours=None):  # noqa: E501
        """PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours - a model defined in Swagger"""  # noqa: E501
        self._enable = None
        self._reset = None
        self._time_zone = None
        self._allow_internal_calls = None
        self._restricted_hours = None
        self._restricted_holiday_hours = None
        self.discriminator = None
        if enable is not None:
            self.enable = enable
        if reset is not None:
            self.reset = reset
        if time_zone is not None:
            self.time_zone = time_zone
        if allow_internal_calls is not None:
            self.allow_internal_calls = allow_internal_calls
        if restricted_hours is not None:
            self.restricted_hours = restricted_hours
        if restricted_holiday_hours is not None:
            self.restricted_holiday_hours = restricted_holiday_hours

    @property
    def enable(self):
        """Gets the enable of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501

        Whether to define when the user cannot make or accept calls and send SMS. In the restricted hours, calls will follow \"When a call is not answered\" settings. Outbound and inbound emergency calls will still be allowed.  # noqa: E501

        :return: The enable of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.

        Whether to define when the user cannot make or accept calls and send SMS. In the restricted hours, calls will follow \"When a call is not answered\" settings. Outbound and inbound emergency calls will still be allowed.  # noqa: E501

        :param enable: The enable of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: bool
        """

        self._enable = enable

    @property
    def reset(self):
        """Gets the reset of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501

        Whether the user's ad hoc recording reset option will use the phone site's settings.  # noqa: E501

        :return: The reset of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: bool
        """
        return self._reset

    @reset.setter
    def reset(self, reset):
        """Sets the reset of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.

        Whether the user's ad hoc recording reset option will use the phone site's settings.  # noqa: E501

        :param reset: The reset of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: bool
        """

        self._reset = reset

    @property
    def time_zone(self):
        """Gets the time_zone of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501


        :return: The time_zone of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursTimeZone
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone):
        """Sets the time_zone of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.


        :param time_zone: The time_zone of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursTimeZone
        """

        self._time_zone = time_zone

    @property
    def allow_internal_calls(self):
        """Gets the allow_internal_calls of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501

        Whether to allow internal calls/SMS during restricted hours.  # noqa: E501

        :return: The allow_internal_calls of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: bool
        """
        return self._allow_internal_calls

    @allow_internal_calls.setter
    def allow_internal_calls(self, allow_internal_calls):
        """Sets the allow_internal_calls of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.

        Whether to allow internal calls/SMS during restricted hours.  # noqa: E501

        :param allow_internal_calls: The allow_internal_calls of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: bool
        """

        self._allow_internal_calls = allow_internal_calls

    @property
    def restricted_hours(self):
        """Gets the restricted_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501


        :return: The restricted_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHours
        """
        return self._restricted_hours

    @restricted_hours.setter
    def restricted_hours(self, restricted_hours):
        """Sets the restricted_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.


        :param restricted_hours: The restricted_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHours
        """

        self._restricted_hours = restricted_hours

    @property
    def restricted_holiday_hours(self):
        """Gets the restricted_holiday_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501


        :return: The restricted_holiday_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :rtype: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHolidayHours
        """
        return self._restricted_holiday_hours

    @restricted_holiday_hours.setter
    def restricted_holiday_hours(self, restricted_holiday_hours):
        """Sets the restricted_holiday_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.


        :param restricted_holiday_hours: The restricted_holiday_hours of this PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours.  # noqa: E501
        :type: PhonecommonAreascommonAreaIdpoliciespolicyTypeRestrictedCallHoursRestrictedHolidayHours
        """

        self._restricted_holiday_hours = restricted_holiday_hours

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhoneusersuserIdpoliciespolicyTypeRestrictedCallHours):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
