# coding: utf-8

"""
    Zoom Phone API

    The Zoom Phone API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [OAuth](https://developers.zoom.us/docs/integrations/oauth/) documentation. All endpoints are available via `https` and are located at `api.zoom.us/v2/`.  For instance, you can list all users on an account via `https://api.zoom.us/v2/users/`.  **Note**: You will get `403` response `Zoom Phone has not been enabled for this account` if the phone account is not set up.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PhonesitessiteIdPolicyCallPark(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'call_not_picked_up_action': 'int',
        'enable': 'bool',
        'reset': 'bool',
        'locked': 'bool',
        'expiration_period': 'int',
        'forward_to_extension_id': 'str',
        'sequence': 'int'
    }

    attribute_map = {
        'call_not_picked_up_action': 'call_not_picked_up_action',
        'enable': 'enable',
        'reset': 'reset',
        'locked': 'locked',
        'expiration_period': 'expiration_period',
        'forward_to_extension_id': 'forward_to_extension_id',
        'sequence': 'sequence'
    }

    def __init__(self, call_not_picked_up_action=None, enable=None, reset=None, locked=None, expiration_period=None, forward_to_extension_id=None, sequence=None):  # noqa: E501
        """PhonesitessiteIdPolicyCallPark - a model defined in Swagger"""  # noqa: E501
        self._call_not_picked_up_action = None
        self._enable = None
        self._reset = None
        self._locked = None
        self._expiration_period = None
        self._forward_to_extension_id = None
        self._sequence = None
        self.discriminator = None
        if call_not_picked_up_action is not None:
            self.call_not_picked_up_action = call_not_picked_up_action
        if enable is not None:
            self.enable = enable
        if reset is not None:
            self.reset = reset
        if locked is not None:
            self.locked = locked
        if expiration_period is not None:
            self.expiration_period = expiration_period
        if forward_to_extension_id is not None:
            self.forward_to_extension_id = forward_to_extension_id
        if sequence is not None:
            self.sequence = sequence

    @property
    def call_not_picked_up_action(self):
        """Gets the call_not_picked_up_action of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        The action when a parked call is not picked up.   `100` - Ring back to parker  `0` - Forward to voicemail of the parker  `9` - Disconnect   `50` - Forward to another extension  # noqa: E501

        :return: The call_not_picked_up_action of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: int
        """
        return self._call_not_picked_up_action

    @call_not_picked_up_action.setter
    def call_not_picked_up_action(self, call_not_picked_up_action):
        """Sets the call_not_picked_up_action of this PhonesitessiteIdPolicyCallPark.

        The action when a parked call is not picked up.   `100` - Ring back to parker  `0` - Forward to voicemail of the parker  `9` - Disconnect   `50` - Forward to another extension  # noqa: E501

        :param call_not_picked_up_action: The call_not_picked_up_action of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: int
        """

        self._call_not_picked_up_action = call_not_picked_up_action

    @property
    def enable(self):
        """Gets the enable of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        Whether to allow calls placed on hold to be resumed from another location using a retrieval code.  # noqa: E501

        :return: The enable of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this PhonesitessiteIdPolicyCallPark.

        Whether to allow calls placed on hold to be resumed from another location using a retrieval code.  # noqa: E501

        :param enable: The enable of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: bool
        """

        self._enable = enable

    @property
    def reset(self):
        """Gets the reset of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        Whether the current settings will use the phone account's settings (applicable if the current settings are using the new policy framework).  # noqa: E501

        :return: The reset of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: bool
        """
        return self._reset

    @reset.setter
    def reset(self, reset):
        """Sets the reset of this PhonesitessiteIdPolicyCallPark.

        Whether the current settings will use the phone account's settings (applicable if the current settings are using the new policy framework).  # noqa: E501

        :param reset: The reset of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: bool
        """

        self._reset = reset

    @property
    def locked(self):
        """Gets the locked of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        Whether the senior administrator allows users to modify the current settings.  # noqa: E501

        :return: The locked of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this PhonesitessiteIdPolicyCallPark.

        Whether the senior administrator allows users to modify the current settings.  # noqa: E501

        :param locked: The locked of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: bool
        """

        self._locked = locked

    @property
    def expiration_period(self):
        """Gets the expiration_period of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        A time limit for parked calls in minutes. After the expiration period ends, the retrieval code is no longer valid and a new code will be generated.  # noqa: E501

        :return: The expiration_period of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: int
        """
        return self._expiration_period

    @expiration_period.setter
    def expiration_period(self, expiration_period):
        """Sets the expiration_period of this PhonesitessiteIdPolicyCallPark.

        A time limit for parked calls in minutes. After the expiration period ends, the retrieval code is no longer valid and a new code will be generated.  # noqa: E501

        :param expiration_period: The expiration_period of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]  # noqa: E501
        if expiration_period not in allowed_values:
            raise ValueError(
                "Invalid value for `expiration_period` ({0}), must be one of {1}"  # noqa: E501
                .format(expiration_period, allowed_values)
            )

        self._expiration_period = expiration_period

    @property
    def forward_to_extension_id(self):
        """Gets the forward_to_extension_id of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        The extension's forwarding information when `call_not_picked_up_action` uses the `50` - Forward to another extension.  # noqa: E501

        :return: The forward_to_extension_id of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: str
        """
        return self._forward_to_extension_id

    @forward_to_extension_id.setter
    def forward_to_extension_id(self, forward_to_extension_id):
        """Sets the forward_to_extension_id of this PhonesitessiteIdPolicyCallPark.

        The extension's forwarding information when `call_not_picked_up_action` uses the `50` - Forward to another extension.  # noqa: E501

        :param forward_to_extension_id: The forward_to_extension_id of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: str
        """

        self._forward_to_extension_id = forward_to_extension_id

    @property
    def sequence(self):
        """Gets the sequence of this PhonesitessiteIdPolicyCallPark.  # noqa: E501

        Only used in the new policy framework. Choose how parked calls are assigned to a BLF (Busy Lamp Field) key. Sequential assignment will park the call at the next available BLF key. Random assignment will park the call at a randomly selected BLF key.  `0` - Random  `1` - Sequential  # noqa: E501

        :return: The sequence of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :rtype: int
        """
        return self._sequence

    @sequence.setter
    def sequence(self, sequence):
        """Sets the sequence of this PhonesitessiteIdPolicyCallPark.

        Only used in the new policy framework. Choose how parked calls are assigned to a BLF (Busy Lamp Field) key. Sequential assignment will park the call at the next available BLF key. Random assignment will park the call at a randomly selected BLF key.  `0` - Random  `1` - Sequential  # noqa: E501

        :param sequence: The sequence of this PhonesitessiteIdPolicyCallPark.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1]  # noqa: E501
        if sequence not in allowed_values:
            raise ValueError(
                "Invalid value for `sequence` ({0}), must be one of {1}"  # noqa: E501
                .format(sequence, allowed_values)
            )

        self._sequence = sequence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PhonesitessiteIdPolicyCallPark, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PhonesitessiteIdPolicyCallPark):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
